######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 21 07:03:40 2010
######################################################################

TEMPLATE = app
TARGET = balaqt
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += balaqt.cpp \
    mainwindow.cpp

include(install.pri)

HEADERS += \
    mainwindow.h

FORMS += \
    mainwindow.ui
